<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Hybrid' => array($vendorDir . '/hybridauth/hybridauth/hybridauth'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src'),
);
