<?php

// Generated by TranslationBrowser  20091102-04:24:44 PM

$french = array( 
	 'tasks'  =>  "Tâches" , 
	 'tasks:add'  =>  "Créer une tâche" , 
	 'tasks:read'  =>  "Tâches de %s" , 
	 'tasks:friends'  =>  "Tâches des amis" , 
	 'tasks:everyone'  =>  "Toutes les tâches" , 
	 'tasks:this'  =>  "Ajouter aux tâches" , 
	 'tasks:this:group'  =>  "Tâches dans %s" , 
	 'tasks:tasklet'  =>  "Obtenir le tasklet" , 
	 'tasks:tasklet:group'  =>  "Les tâches du groupe" , 
	 'tasks:inbox'  =>  "Tâches en attente" , 
	 'tasks:more'  =>  "Plus" , 
	 'tasks:shareditem'  =>  "Tâches" , 
	 'tasks:with'  =>  "Partager ceci" , 
	 'tasks:new'  =>  "Nouvelle tâche" , 
	 'tasks:via'  =>  "via tâche" ,
	 'tasks:owner' => "Tâches de %s",
	 'tasks:none' => "Aucune Tâche",	 
	 
	 'tasks:delete:confirm'  =>  "Etes-vous sur de supprimer cette tâche?" , 
	 'tasks:numbertodisplay'  =>  "Nombre de tâches à afficher" , 
	 'tasks:shared'  =>  "tâche" , 
	 
	 'tasks:recent'  =>  "Tâches récentes" , 
	 'tasks:river:created'  =>  "%s marqué comme tâche" , 
	 'tasks:river:annotate'  =>  "à écrit un commentaire sur votre tâche" , 
	 'tasks:river:item'  =>  "un item" , 
	 'item:object:tasks'  =>  "Tâches" , 
	 'tasks:group'  =>  "Tâches de groupe" , 
	 'tasks:enabletasks'  =>  "Autoriser les tâches de groupe" , 
	 'tasks:widget:description'  =>  "Ce widget est conçu pour votre tableau de bord et vous affichera les derniers tâches dans votre boîte à tâches." , 
	 'tasks:save:success'  =>  "Votre tâche a été correctement créée." , 
	 'tasks:delete:success'  =>  "Votre tâche a été correctement supprimée." , 
	 'tasks:save:failed'  =>  "Votre tâche n'a pas été correctement créé. Essayez encore une fois." , 
	 'tasks:delete:failed'  =>  "Votre tâche n'a pas été correctement supprimée. Essayez encore une fois.",
	 'tasks:add' => "Ajouter une tâche",
	 
	 'tasks:start_date' => "Début",
	 'tasks:end_date' => "Fin",
	 'tasks:percent_done' => " fait",
	 'tasks:work_remaining' => "Reste",
	 

	 'tasks:task_type' => 'Type',
	 'tasks:status' => 'Etat',
	 'tasks:assigned_to' => 'Assigné à',
	 
	 'tasks:task_type_'=>"",
	 'tasks:task_type_0'=>"",
	 'tasks:task_type_1'=>"Analyse",
	 'tasks:task_type_2'=>"Réalisation",
	 'tasks:task_type_3'=>"Développement",
	 'tasks:task_type_4'=>"Recette",
	 'tasks:task_type_5'=>"Mise en production",
	 
	 'tasks:task_status_'=>"",
	 'tasks:task_status_0'=>"",
	 'tasks:task_status_1'=>"Ouvert",
	 'tasks:task_status_2'=>"Assigné",
	 'tasks:task_status_3'=>"Estimé",
	 'tasks:task_status_4'=>"En cours",
	 'tasks:task_status_5'=>"Fermé",
	 
	 'tasks:task_percent_done_'=>"0%",
	 'tasks:task_percent_done_0'=>"0%",
	 'tasks:task_percent_done_1'=>"20%",
	 'tasks:task_percent_done_2'=>"40%",
	 'tasks:task_percent_done_3'=>"60%",
	 'tasks:task_percent_done_4'=>"80%",
	 'tasks:task_percent_done_5'=>"100%",
	 
	 'tasks:access' => "Acc&egrave;s",
	 'tasks:write_access' => "Acc&egrave;s en &eacute;criture",
	 
	 'tasks:tasksboard'=>"TasksBoard",
	 'tasks:tasksmanage'=>"Gérer",
	 'tasks:tasksmanageone'=>"Gérer une tâche",
			
); 

add_translation('fr', $french); 

?>