apiVersion: v1
kind: Service
metadata:
  name: {{ include "collab.fullname" . }}-memcached
  labels:
    app.kubernetes.io/name: {{ include "collab.name" . }}-memcached
    helm.sh/chart: {{ include "collab.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.memcached.service.type }}
{{- if .Values.memcached.service.clusterIP }}
  clusterIP: "{{ .Values.memcached.service.clusterIP }}"
{{- end }}
  ports:
    - port: {{ .Values.memcached.service.port }}
      targetPort: memcached
      protocol: TCP
      name: memcached
  selector:
    app.kubernetes.io/name: {{ include "collab.name" . }}-memcached
    app.kubernetes.io/instance: {{ .Release.Name }}
