{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.tls }}
{{- $fullName := include "collab.fullname" . -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ $fullName }}-tls-secret
spec:
  secretName: {{ $fullName }}-tls-secret
  dnsNames:
      - {{ .Values.host }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
        - {{ .Values.host }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
{{- end }}
{{- end }}