{{- if .Values.ingress.tls }}
{{- $fullName := include "collab.fullname" . -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ $fullName }}-tls-secret
spec:
  secretName: {{ $fullName }}-tls-secret
  {{- range .Values.ingress.tls.hosts }}
  dnsNames:
      - {{ . | quote }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
        - {{ . | quote }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  {{- end }}
{{- end }}