apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "collab.fullname" . }}-env"
  labels:
    app: {{ template "collab.name" . }}
    chart: {{ template "collab.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
{{- if .Values.mariadb.user }}
  db-user: {{ .Values.mariadb.auth.user | b64enc | quote }}
{{ else }}
  db-user: {{ "collab" | b64enc | quote }}
{{- if .Values.mariadb.password }}
  db-root: {{ .Values.mariadb.auth.root | b64enc | quote }}
{{ else }}
  db-root: {{ randAlphaNum 10 | b64enc | quote }}
{{- end -}}
{{- if .Values.mariadb.password }}
  db-password: {{ .Values.mariadb.auth.password | b64enc | quote }}
{{ else }}
  db-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end -}}
{{- end -}}