apiVersion: v1
kind: Service
metadata:
  name: {{ include "collab.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "collab.name" . }}
    helm.sh/chart: {{ include "collab.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.clusterIP }}
  clusterIP: "{{ .Values.service.clusterIP }}"
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "collab.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
